# name: Execução de testes

# on:
#  push:
#    branches: [ main ]
 # pull_request:
  #  branches: [ main ]
#  schedule:
#    - cron: '0 9,11,15,18 * * 1,2,3,4,5'
      
#jobs:
#  e2e-tests:
#    runs-on: windows-latest

#    steps:
#      - name: Checkout projeto
#       uses: actions/checkout@v4
      
#      - name: Setup Node.js enviroment
#        uses: actions/setup-node@v4
#        with:
#          node-version: '20.x'

#      - name: Install dependecies
#        run: npm ci
#      - name: Run Cypress tests
#        run: npx cypress run
#      - uses: actions/upload-artifact@v4
#        # add the line below to store screenshots only on failures
#        if: failure()
#        with:
#          name: cypress-screenshots
#          path: cypress/screenshots
#          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
#      - uses: actions/upload-artifact@v4
#        with:
#          name: cypress-videos
#          path: cypress/videos
#          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
