name: Execução de testes de Adicionando Notas

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
    schedule:
      - cron: '0 8,10,12,14,15 * * 1,2,3,4,5'
      
jobs:
  e2e-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout projeto
        uses: actions/checkout@v2
      
      - name: Setup Node.js enviroment
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 18.
        
      - name: Install dependecies
        run: npm ci
      - name: Run AddNota tests
        run: npx condeceptjs run